apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-mpsq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0059-tenant/tkrw-pr712-0075-0059-app/devfile-sample-mpsq@sha256:e8c4b9e9328879dbcec3540cba54e800d8ae3390cb3317fbafbfcaf3bcce8c49
        name: my-nodejs
        resources: {}
status: {}
